site_name: Docs
site_dir: ../../dist/docs/
site_url: https://joaquingottlebe.com
repo_url: https://github.com/Huaqo/website
repo_name: huaqo/website
edit_uri: edit/main/src/docs/docs/
theme:
  name: material
  custom_dir: overrides
  features:
    #- announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Fira Code
    code: Fira Code
  favicon: ../assets/images/favicon-32x32.png

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - DevTools:
    - devtools/index.md
    - devtools/git.md
    - devtools/github_actions.md
    - devtools/homebrew.md
    - devtools/neovim.md
    - devtools/tmux.md
    - devtools/tree.md
    - Python:
      - devtools/pip.md
      - devtools/venv.md
  - GameDev:
    - gamedev/index.md
    - C/C++:
      - gamedev/raygui.md
      - gamedev/raylib.md
    - Godot:
      - gamedev/gdscript.md
    - Python:
      - gamedev/pygame.md
  - GeoDev:
    - geodev/index.md
    - JavaScript:
      - geodev/leaflet.md
    - Python:
      - geodev/folium.md
      - geodev/geopandas.md
      - geodev/pyqgis.md
    - R:
      - geodev/orfeo_toolbox.md
      - geodev/random_forest.md
      - geodev/rstoolbox.md
      - geodev/terra.md
  - Languages:
    - languages/index.md
    - languages/c.md
    - languages/cpp.md
    - languages/css.md
    - languages/html.md
    - languages/javascript.md
    - languages/python.md
    - languages/r.md
  - SciDev:
    - scidev/index.md
    - scidev/matplotlib.md
    - scidev/numpy.md
    - scidev/pandas.md
    - scidev/scipy.md
    - scidev/seaborn.md
  - WebDev:
    - webdev/index.md
    - Python:
      - webdev/flask.md
      - webdev/jinja.md
      - webdev/json.md
    - SQL:
      - webdev/sqlite.md
      - webdev/sqlite3.md
      - webdev/postgresql.md
    - Tools:
      - webdev/http-server.md
  - Writing:
    - writing/index.md
    - writing/latex.md
    - writing/markdown.md
    - writing/mermaid.md
    - writing/pandoc.md