site_name: Docs
site_dir: ../../dist/docs/
site_url: https://joaquingottlebe.com
repo_url: https://github.com/Huaqo/website
repo_name: huaqo/website
edit_uri: edit/main/src/docs/docs/
theme:
  name: material
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Fira Code
    code: Fira Code
  favicon: ../assets/images/favicon-32x32.png

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - DevTools:
    - Git.md
    - github_actions.md
    - Homebrew.md
    - Neovim.md
    - Tmux.md
    - Tree.md
    - Python:
      - Pip.md
      - venv.md
  - GameDev:
    - C/C++:
      - raygui.md
      - raylib.md
    - Godot:
      - gdscript.md
    - Python:
      - pygame.md
  - GeoDev:
    - JavaScript:
      - leaflet.md
    - Python:
      - folium.md
      - geopandas.md
      - PyQGIS.md
    - R:
      - gdal.md
      - orfeo_toolbox.md
      - random_forest.md
      - rstoolbox.md
      - terra.md
  - Languages:
    - C.md
    - C++.md
    - CSS.md
    - HTML.md
    - Javascript.md
    - Python.md
    - R.md
  - SciDev:
    - matplotlib.md
    - numpy.md
    - pandas.md
    - scipy.md
    - seaborn.md
  - WebDev:
    - Python:
      - Flask.md
      - Jinja2.md
      - json.md
    - SQL:
      - SQLite.md
      - SQLite3.md
      - Postgresql.md
    - Tools:
      - Http-server.md
  - Writing:
    - Latex.md
    - markdown.md
    - Mermaid.md
    - pandoc.md
    