site_name: Docs
site_dir: ../../dist/docs/
site_url: https://joaquingottlebe.com
repo_url: https://github.com/Huaqo/website
repo_name: huaqo/website
edit_uri: edit/main/src/docs/docs/
copyright: Copyright &copy; 2024 Joaquin Gottlebe
theme:
  name: material
  features:
    #- announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
#    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Fira Code
    code: Fira Code
  favicon: ../assets/images/favicon-32x32.png

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - index.md
  - c.md
  - cpp.md
  - css.md
  - flask.md
  - folium.md
  - gdscript.md
  - geopandas.md
  - git.md
  - github_actions.md
  - homebrew.md
  - html.md
  - http-server.md
  - javascript.md
  - jinja.md
  - json.md
  - latex.md
  - leaflet.md
  - markdown.md
  - matplotlib.md
  - mermaid.md
  - neovim.md
  - numpy.md
  - orfeo_toolbox.md
  - pandas.md
  - pandoc.md
  - pip.md
  - postgresql.md
  - pyqgis.md
  - pygame.md
  - python.md
  - random_forest.md
  - raygui.md
  - raylib.md
  - r.md
  - rstoolbox.md
  - scipy.md
  - seaborn.md
  - sqlite.md
  - sqlite3.md
  - terra.md
  - tmux.md
  - tree.md
  - venv.md
