site_name: Docs
site_dir: ../../dist/docs/
site_url: https://joaquingottlebe.com
repo_url: https://github.com/Huaqo/website
repo_name: huaqo/website
edit_uri: edit/main/src/docs/docs/
copyright: Copyright &copy; 2024 Joaquin Gottlebe
theme:
  name: material
  features:
    #- announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.footnote.tooltips
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
#    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    # - navigation.prune
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    # - toc.integrate
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: black
      accent: teal
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: teal
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
  font:
    text: Fira Code
    code: Fira Code
  favicon: ../assets/images/favicon-32x32.png

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - Tools:
    - git.md
    - github_actions.md
    - homebrew.md
    - http-server.md
    - neovim.md
    - pip.md
    - tmux.md
    - tree.md
    - venv.md
    - zsh.md
  - Games:
    - gdscript.md
    - pygame.md
    - raygui.md
    - raylib.md
  - Geographie:
    - folium.md
    - geopandas.md
    - leaflet.md
    - orfeo_toolbox.md
    - pyqgis.md
    - random_forest.md
    - rstoolbox.md
    - terra.md
  - Languages:
    - c.md
    - cpp.md
    - css.md
    - html.md
    - javascript.md
    - python.md
    - r.md
  - Scientific:
    - matplotlib.md
    - numpy.md
    - pandas.md
    - scipy.md
    - seaborn.md
  - Web:
    - flask.md
    - jinja.md
    - json.md
    - postgresql.md
    - sqlite.md
    - sqlite3.md
  - Writing:
    - latex.md
    - markdown.md
    - mermaid.md
    - pandoc.md
